# Generated by Django 5.0.14 on 2026-07-21 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpack',
            name='price_xof',
            field=models.DecimalField(decimal_places=2, help_text='Prix en FCFA (min 500).', max_digits=10, validators=[django.core.validators.MinValueValidator(500)]),
        ),
    ]
