# Generated by Django 5.0.14 on 2026-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deepseek_api_key', models.CharField(blank=True, help_text='Laisser vide pour utiliser DEEPSEEK_API_KEY (.env).', max_length=200)),
                ('deepseek_api_base', models.CharField(blank=True, max_length=200)),
                ('deepseek_model', models.CharField(blank=True, max_length=100)),
                ('deepseek_embedding_model', models.CharField(blank=True, max_length=100)),
                ('fedapay_environment', models.CharField(blank=True, choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10)),
                ('fedapay_public_key', models.CharField(blank=True, max_length=200)),
                ('fedapay_secret_key', models.CharField(blank=True, max_length=200)),
                ('fedapay_webhook_secret', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration (FedaPay / DeepSeek)',
                'verbose_name_plural': 'Configuration (FedaPay / DeepSeek)',
            },
        ),
    ]
