# Generated by Django 5.0.14 on 2026-07-21 20:14

from django.db import migrations, models

OLD_TO_NEW = {
    "COLLEGE": "AUTRE",
    "LYCEE": "AUTRE",
    "TERMINALE": "APRES_BAC",
    "BAC_OBTENU": "APRES_BAC",
    "UNIVERSITE": "APRES_LICENCE",
    "CHERCHEUR_EMPLOI": "AUTRE",
}


def remap_forward(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    for old, new in OLD_TO_NEW.items():
        Profile.objects.filter(level=old).update(level=new)


def remap_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('APRES_BAC', 'Après le Bac'), ('APRES_LICENCE', 'Après la Licence'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.RunPython(remap_forward, remap_backward),
    ]
